from datetime import datetime
from typing import Protocol

from siniestros.avisos.domain.models import Aviso, Evidencia, ObjetoGuardado


class AvisoRepository(Protocol):
    def add_aviso(self, aviso: Aviso) -> None: ...

    def get_aviso(self, aviso_id: str) -> Aviso | None: ...

    def add_evidencia(self, evidencia: Evidencia) -> None: ...

    def update_evidencia(self, evidencia: Evidencia) -> None: ...

    def get_evidencia(self, aviso_id: str, evidencia_id: str) -> Evidencia | None: ...

    def list_evidencias(self, aviso_id: str) -> list[Evidencia]: ...

    def count_activas(self, aviso_id: str) -> int: ...


class ObjectStore(Protocol):
    def presign_put(self, key: str, content_type: str, size: int) -> tuple[str, dict[str, str], datetime]: ...

    def head(self, key: str) -> ObjetoGuardado | None: ...

    def read_header(self, key: str) -> bytes: ...

    def presign_get(self, key: str) -> str: ...


class FileScanner(Protocol):
    def scan(self, key: str, header: bytes, content_type: str) -> str: ...
