from typing import Protocol

from cotizacion.catalogo.domain.models import Cobertura, Producto, Ramo


class CatalogoRepository(Protocol):
    def list_ramos(self) -> list[Ramo]: ...

    def list_productos(self) -> list[Producto]: ...

    def list_coberturas(self, producto_id: str | None = None) -> list[Cobertura]: ...

    def get_producto(self, producto_id: str) -> Producto | None: ...

    def get_ramo(self, ramo_id: str) -> Ramo | None: ...

    def upsert_ramo(self, ramo: Ramo) -> None: ...

    def upsert_producto(self, producto: Producto) -> None: ...

    def upsert_cobertura(self, cobertura: Cobertura) -> None: ...
