apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: solventa
  labels:
    app: gateway
    experimento: "1"
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: http
