# Generado a partir del modelo de componentes VC-003 v2.0. Editar a mano es válido.
apiVersion: v1
kind: ConfigMap
metadata:
  name: solventa-services
data:
  HEALTH_TARGETS: bff-web,bff-movil,api-socios,cotizacion-rating,validador-consenso,suscripcion,polizas,catalogo-productos,perfilamiento,identidad-kyc,siniestros,siniestro-parametrico,cobros-pagos,socios-gobierno-api,analitica-fraude,notificaciones,reaseguro,auditoria-linaje
  CONSENSO_URL: http://validador-consenso
  POLIZAS_URL: http://polizas
  SINIESTROS_URL: http://siniestros
  GOBIERNO_SOCIOS_URL: http://socios-gobierno-api
  COTIZACION_REPLICAS_HOST: cotizacion-rating-replicas
