[project]
name = "notificaciones"
version = "0.1.0"
description = "Notificaciones: Push, correo, SMS, firma electrónica."
requires-python = ">=3.11"
dependencies = ["solventa-common"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
