export const texts = {
  claims: {
    screenTitle: 'Siniestros',
    emptyMessage: 'Aún no tienes reportes.',
    reportButton: 'Reportar siniestro',
  },
  report: {
    screenTitle: 'Reportar siniestro',
    policyLabel: 'Póliza afectada',
    claimTypeLabel: 'Tipo de siniestro',
    occurredAtLabel: 'Fecha y hora de ocurrencia',
    locationLabel: 'Ubicación',
    locationPending: 'Obteniendo ubicación',
    locationUnavailable: 'No se pudo obtener la ubicación',
    refreshLocation: 'Actualizar ubicación',
    descriptionLabel: 'Descripción',
    descriptionPlaceholder: 'Describe lo ocurrido',
    evidenceHeading: 'Evidencias',
    evidenceHint:
      'Videos de máximo 30 s y 50 MB. Los archivos se comprimen en tu teléfono antes de enviarse.',
    takePhotoButton: 'Tomar foto',
    recordVideoButton: 'Grabar video',
    submitButton: 'Enviar reporte',
    sendFailed: 'No se pudo enviar el reporte.',
    missingEvidence: 'Agrega al menos una evidencia',
    evidenceLimit: 'Este reporte ya tiene 10 evidencias.',
    fileTooLarge: 'El archivo supera 50 MB.',
  },
  camera: {
    screenTitle: 'Tomar foto',
    previewTitle: 'Vista previa',
    viewfinderLabel: 'Cámara',
    framingHint: 'Encuadra el daño y captura',
    cancelButton: 'Cancelar',
    captureButton: 'Capturar',
    confirmButton: 'Confirmar',
  },
  video: {
    screenTitle: 'Grabar video',
    previewTitle: 'Vista previa',
    durationLimit: 'Máximo 30 s',
    recordButton: 'Grabar',
    stopButton: 'Detener',
    cancelButton: 'Cancelar',
    confirmButton: 'Confirmar',
    playButton: 'Reproducir',
    pauseButton: 'Pausar',
  },
  savedPhoto: {
    screenTitle: 'Evidencia',
    removeButton: 'Eliminar',
  },
  detail: {
    screenTitle: 'Detalle del reporte',
    status: 'Radicado',
    assistButton: 'Solicitar asistencia en sitio',
    filedSuccess: (radicado: string) => `Siniestro #${radicado} radicado exitosamente.`,
    occurred: (datetime: string, location: string) =>
      location === '' ? `Ocurrió ${datetime}` : `Ocurrió ${datetime} · ${location}`,
    evidences: (count: number) => `Evidencias (${count})`,
  },
  savedVideo: {
    screenTitle: 'Evidencia',
    removeButton: 'Eliminar',
    playButton: 'Reproducir',
    pauseButton: 'Pausar',
  },
};
