import {
  Ambulance,
  Ban,
  Bell,
  Box,
  Briefcase,
  Calculator,
  Calendar,
  Camera,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  CircleX,
  Clock,
  CloudRain,
  Code,
  CreditCard,
  FileExclamationPoint,
  FileText,
  Funnel,
  Heart,
  House,
  HouseHeart,
  Info,
  Key,
  Layers,
  LayoutGrid,
  Lock,
  MapPin,
  Menu,
  Monitor,
  Notebook,
  Palette,
  Pencil,
  Plane,
  Plus,
  RefreshCw,
  RotateCcw,
  Search,
  Send,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Trash,
  TriangleAlert,
  Truck,
  Type,
  User,
  UserCheck,
  Users,
  Video,
  Wallet,
  Wifi,
  WifiOff,
  X,
  type LucideIcon,
} from 'lucide-react-native';

export const icons = {
  inicio: House,
  polizas: ShieldCheck,
  siniestros: FileExclamationPoint,
  comprar: ShoppingBag,
  operaciones: Briefcase,
  socios: Users,
  menu: Menu,
  volver: ChevronLeft,
  siguiente: ChevronRight,
  desplegar: ChevronDown,
  cerrar: X,
  buscar: Search,
  filtro: Funnel,
  agregar: Plus,
  editar: Pencil,
  cancelar: Ban,
  eliminar: Trash,
  enviar: Send,
  camara: Camera,
  video: Video,
  repetir: RotateCcw,
  sincronizar: RefreshCw,
  exito: CircleCheck,
  info: Info,
  advertencia: TriangleAlert,
  error: CircleX,
  pendiente: Clock,
  enLinea: Wifi,
  sinConexion: WifiOff,
  notificacion: Bell,
  cotizacion: Calculator,
  pago: CreditCard,
  documento: FileText,
  consentimiento: Lock,
  credencial: Key,
  api: Code,
  ubicacion: MapPin,
  grua: Truck,
  ambulancia: Ambulance,
  perito: UserCheck,
  calendario: Calendar,
  usuario: User,
  viaje: Plane,
  dispositivos: Smartphone,
  microseguroVida: Heart,
  parametrico: CloudRain,
  proteccionPagos: Wallet,
  vidaHipotecario: HouseHeart,
  web: Monitor,
  movil: Smartphone,
  designSystem: Layers,
  historias: Notebook,
  paleta: Palette,
  tipografia: Type,
  componentes: Box,
  cuadricula: LayoutGrid,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
