apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-nginx
  namespace: solventa
  labels:
    app: gateway
    experimento: "1"
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        location = /gateway/health {
            default_type text/plain;
            return 200 'ok';
        }

        location / {
            proxy_pass http://cotizacion:8000;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header Connection "";
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
